export const Users = [
  {
    id: 1,
    profilePricture: "assets/person/1.jpg",
    username: "Tomal Kazi",
  },
  {
    id: 2,
    profilePricture: "assets/person/2.jpg",
    username: "Shohanur Rahman",
  },
  {
    id: 3,
    profilePricture: "assets/post/3.jpg",
    username: "Sunzidul Islam",
  },
  {
    id: 4,
    profilePricture: "assets/person/4.jpg",
    username: "Rony Molla",
  },
  {
    id: 5,
    profilePricture: "assets/person/5.jpg",
    username: "Jhon Limon",
  },
  {
    id: 6,
    profilePricture: "assets/person/6.jpg",
    username: "Shahab Uddin",
  },
  {
    id: 7,
    profilePricture: "assets/person/1.jpg",
    username: "Ashikur Rahman",
  },
  {
    id: 8,
    profilePricture: "assets/person/2.jpg",
    username: "Mahadi Hasan",
  },

  {
    id: 9,
    profilePricture: "assets/person/3.jpg",
    username: "Shohan Pramanik",
  },
];

export const Posts = [
  {
    id: 1,
    name: "Tomal Kazi",
    desc: "How are you dear Friend's",
    photo: "assets/post/1.jpg",
    date: "5 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    name: "Shohan Pramanik",
    desc: "No Caption :)",
    photo: "assets/post/2.jpg",
    date: "12 min ago",
    userId: 2,
    like: 45,
    comment: 12,
  },
  {
    id: 3,
    name: "Sunzidul Islam",
    desc: "This is my first Post!",
    photo: "assets/post/3.jpg",
    date: "15 min ago",
    userId: 3,
    like: 55,
    comment: 8,
  },
  {
    id: 4,
    name: "Ashikur Rahman",
    desc: "It that good!",
    photo: "assets/post/4.jpg",
    date: "13 min ago",
    userId: 4,
    like: 32,
    comment: 6,
  },
  {
    id: 5,
    name: "Jhon Limon",
    desc: "Happy Moment!",
    photo: "assets/person/5.jpg",
    date: "25 min ago",
    userId: 5,
    like: 44,
    comment: 34,
  },
  {
    id: 6,
    name: "Nurse Shahab",
    desc: "My Friend",
    photo: "assets/person/6.jpg",
    date: "45 min ago",
    userId: 6,
    like: 56,
    comment: 34,
  },
  {
    id: 7,
    name: "Niyamot Ullah",
    desc: "So pritty!",
    photo: "assets/person/1.jpg",
    date: "1 hour ago",
    userId: 7,
    like: 43,
    comment: 14,
  },
  {
    id: 8,
    name: "Adhar Rater Josna",
    desc: "How are you dear Friend's",
    photo: "assets/person/2.jpg",
    date: "2 hour ago",
    userId: 8,
    like: 32,
    comment: 9,
  },
  {
    id: 9,
    name: "Tomal Kazi",
    desc: "This is my first one post!",
    photo: "assets/person/3.jpg",
    date: "5 hour ago",
    userId: 9,
    like: 45,
    comment: 12,
  },
];
